statsservice:
  #image: kamon/grafana_graphite
  image: hopsoft/graphite-statsd
  ports: 
    - 80:80
    - 8125:8125/udp 
    - 8126:8126
    - 8000:8000
mysql:
  image: mysql:5.6
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: test
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypass
  ports:
    - "3306:3306"
api:
  image: singram/singram-spring-base-app
  ports:
    - "8080:8080"
  environment:
    SPRING_PROFILES_ACTIVE: dev
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/test
    SPRING_METRICS_EXPORT_STATSD_HOST: statsservice
  links:
    - mysql
    - statsservice
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
